---

- name: create R group
  group: 
    name: r
    state: present

- name: add users to r group
  when: (users is defined) and (item.in_r | default(false))
  user:
    name: "{{ item.username }}"
    groups: r
    append: yes
  with_items:
    - "{{ all_users | selectattr('username', 'in', users) | list }}"

# - name: add docker key
#   apt_key:
#     keyserver: keyserver.ubuntu.com
#     id: E084DAB9

#- name: add R repository
#  apt_repository:
#    repo: deb http://mirrors.nic.cz/R/bin/linux/ubuntu/ artful/
#    state: present

- name: set /etc/hosts
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{item}}" state=present
  when: hostvars[item].ansible_host is defined
  with_inventory_hostnames:
    - r

- name: download GNU parallel install script
  get_url:
    url: http://bit.ly/install-gnu-parallel
    dest: /tmp/install-gnu-parallel.sh
    mode: 0755

- name: install latest GNU parallel
  shell: /tmp/install-gnu-parallel.sh
  args:
    creates: /usr/local/bin/parallel
