- name: Add neovim ppa
  apt_repository: repo="ppa:neovim-ppa/unstable" state=present

- name: Install neovim from ppa
  apt:
    update_cache: yes
    state: present
    name:
      - neovim

- name: Use nvim for vi
  alternatives: name=vi path=/usr/bin/nvim

- name: Use nvim for vim
  alternatives: name=vim path=/usr/bin/nvim

- name: Use nvim for editor
  alternatives: name=editor path=/usr/bin/nvim
